"""raza_corregida

Revision ID: 13592105ef47
Revises: 1d5db9e9e5d0
Create Date: 2025-10-15 15:23:09.066325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13592105ef47'
down_revision: Union[str, Sequence[str], None] = '1d5db9e9e5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user',
        'tipo_document_id',  # nombre actual
        new_column_name='type_document_id'  # nuevo nombre
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user',
        'type_document_id',  # nombre actual
        new_column_name='tipo_document_id'  # nombre original
    )
    # ### end Alembic commands ###
