"""relaciones_pet_user

Revision ID: 1d5db9e9e5d0
Revises: 3253893bb2ac
Create Date: 2025-10-11 18:32:55.780946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5db9e9e5d0'
down_revision: Union[str, Sequence[str], None] = '3253893bb2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet', 'breed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet', 'breed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
