"""fix relation clinic service

Revision ID: 1f29c4ffdbc5
Revises: d56aad2def4c
Create Date: 2025-11-21 12:52:02.590082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f29c4ffdbc5'
down_revision: Union[str, Sequence[str], None] = 'd56aad2def4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
