"""vaccinepet relation

Revision ID: 201c018166d7
Revises: b6932ec5bb0e
Create Date: 2025-11-19 20:24:41.001186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201c018166d7'
down_revision: Union[str, Sequence[str], None] = 'b6932ec5bb0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_vaccine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_type_id', sa.Integer(), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('dose', sa.String(), nullable=True),
    sa.Column('batch', sa.String(), nullable=True),
    sa.Column('veterinarian', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['vaccine_type_id'], ['vaccine_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_vaccine')
    # ### end Alembic commands ###
