"""conecton vaccine and pet

Revision ID: 290b5a43fd06
Revises: a2e6bd265f65
Create Date: 2025-11-14 02:29:29.323448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290b5a43fd06'
down_revision: Union[str, Sequence[str], None] = 'a2e6bd265f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
