"""fix relation clinic service v2

Revision ID: 508d8c1d5c06
Revises: 1f29c4ffdbc5
Create Date: 2025-11-21 12:57:47.239866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508d8c1d5c06'
down_revision: Union[str, Sequence[str], None] = '1f29c4ffdbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
