"""relation vaccine pet

Revision ID: 580a1dcfa5ee
Revises: beee392da4b2
Create Date: 2025-11-19 19:15:27.828097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580a1dcfa5ee'
down_revision: Union[str, Sequence[str], None] = 'beee392da4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccine_type', sa.Column('specie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vaccine_type', 'species', ['specie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccine_type', type_='foreignkey')
    op.drop_column('vaccine_type', 'specie_id')
    # ### end Alembic commands ###
