"""apointment pet

Revision ID: 58fb99b01b0b
Revises: ea0de4f2eb09
Create Date: 2025-11-21 10:43:17.345586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fb99b01b0b'
down_revision: Union[str, Sequence[str], None] = 'ea0de4f2eb09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('pet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointment', 'pet', ['pet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'pet_id')
    # ### end Alembic commands ###
