"""fix relation clinic appointment v2

Revision ID: 75b8ce2b154a
Revises: 508d8c1d5c06
Create Date: 2025-11-21 13:04:07.947988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b8ce2b154a'
down_revision: Union[str, Sequence[str], None] = '508d8c1d5c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
