"""fix v2 table vaccine and pet

Revision ID: 80ceab94d269
Revises: 8f1f34f67aa4
Create Date: 2025-11-14 02:38:04.449358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ceab94d269'
down_revision: Union[str, Sequence[str], None] = '8f1f34f67aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
