"""add verification fields to users

Revision ID: 81dc2d97ee25
Revises: 13592105ef47
Create Date: 2025-10-17 00:10:03.600896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dc2d97ee25'
down_revision: Union[str, Sequence[str], None] = '13592105ef47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('verification_code', sa.String(length=5), nullable=True))
    op.add_column('user', sa.Column('verification_expiration', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_expiration')
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
