"""vaccine table

Revision ID: a2e6bd265f65
Revises: 820ea50c025e
Create Date: 2025-11-14 02:28:21.284006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e6bd265f65'
down_revision: Union[str, Sequence[str], None] = '820ea50c025e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breed', 'species_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breed', 'species_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
