"""fix v5 table vaccine and pet

Revision ID: a6a909d5a4f4
Revises: b5a693dbbbd7
Create Date: 2025-11-14 02:45:29.291924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a909d5a4f4'
down_revision: Union[str, Sequence[str], None] = 'b5a693dbbbd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
