"""vaccinepet

Revision ID: b6932ec5bb0e
Revises: 580a1dcfa5ee
Create Date: 2025-11-19 20:21:35.937399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6932ec5bb0e'
down_revision: Union[str, Sequence[str], None] = '580a1dcfa5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vaccine_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], name=op.f('vaccine_pet_id_fkey')),
    sa.ForeignKeyConstraint(['vaccine_type_id'], ['vaccine_type.id'], name=op.f('vaccine_vaccine_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vaccine_pkey'))
    )
    # ### end Alembic commands ###
