"""fix delete pet

Revision ID: c8734bcc2f1f
Revises: 75b8ce2b154a
Create Date: 2025-11-21 14:54:25.426637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8734bcc2f1f'
down_revision: Union[str, Sequence[str], None] = '75b8ce2b154a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pet_vaccine_pet_id_fkey'), 'pet_vaccine', type_='foreignkey')
    op.create_foreign_key(None, 'pet_vaccine', 'pet', ['pet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet_vaccine', type_='foreignkey')
    op.create_foreign_key(op.f('pet_vaccine_pet_id_fkey'), 'pet_vaccine', 'pet', ['pet_id'], ['id'])
    # ### end Alembic commands ###
