"""fix relation appointment pet

Revision ID: d56aad2def4c
Revises: 58fb99b01b0b
Create Date: 2025-11-21 12:46:17.707919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56aad2def4c'
down_revision: Union[str, Sequence[str], None] = '58fb99b01b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic', sa.Column('ruc', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'clinic', ['ruc'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clinic', type_='unique')
    op.drop_column('clinic', 'ruc')
    # ### end Alembic commands ###
