"""clicnis relations

Revision ID: ea0de4f2eb09
Revises: 201c018166d7
Create Date: 2025-11-21 00:10:46.188030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0de4f2eb09'
down_revision: Union[str, Sequence[str], None] = '201c018166d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('services')
    op.add_column('appointment', sa.Column('clinic_id', sa.Integer(), nullable=False))
    op.add_column('appointment', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('appointment', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointment', 'clinic', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'appointment', 'appointment_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'appointment', 'service', ['service_id'], ['id'])
    op.alter_column('clinic', 'webPage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('clinic', 'schedules')
    op.add_column('clinic_services', sa.Column('clinic_id', sa.Integer(), nullable=False))
    op.add_column('clinic_services', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clinic_services', 'clinic', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'clinic_services', 'service', ['service_id'], ['id'])
    op.add_column('schedules', sa.Column('clinic_id', sa.Integer(), nullable=False))
    op.add_column('schedules', sa.Column('day', sa.String(), nullable=False))
    op.add_column('schedules', sa.Column('open_time', sa.Time(), nullable=False))
    op.add_column('schedules', sa.Column('close_time', sa.Time(), nullable=False))
    op.create_foreign_key(None, 'schedules', 'clinic', ['clinic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'close_time')
    op.drop_column('schedules', 'open_time')
    op.drop_column('schedules', 'day')
    op.drop_column('schedules', 'clinic_id')
    op.drop_constraint(None, 'clinic_services', type_='foreignkey')
    op.drop_constraint(None, 'clinic_services', type_='foreignkey')
    op.drop_column('clinic_services', 'service_id')
    op.drop_column('clinic_services', 'clinic_id')
    op.add_column('clinic', sa.Column('schedules', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('clinic', 'webPage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'status_id')
    op.drop_column('appointment', 'service_id')
    op.drop_column('appointment', 'clinic_id')
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('services_pkey'))
    )
    op.drop_table('service')
    # ### end Alembic commands ###
